
الرئيسية
التمدرس
التمدرس
المراقبة المستمرة
تتبع النقط
الغياب
جدولة الامتحانات
مساري الدراسي
الموارد الرقمية
التوجيه
المرحلة الأولية
اختياراتي الدراسية والتكوينية
أهدافي المهنية المستقبلية
ميولي المهنية (استمارة)
ميولي الدراسية (استمارة)
انسجام اختياراتي وجانبياتي

المرحلة النهائية
اختياراتي الدراسية والتكوينية
أهدافي المهنية المستقبلية

إدارة المقابلات
طلب مقابلة المستشار في التوجيه التربوي

إعادة التوجيه
إعادة التوجيه
طلب إعادة التوجيه
تدقيق المعطيات
المساعدة
مسابقات رياضية عن بعد
اسئلة و اجوبة
علبة الأفكار
اشعارات
المستجدات


عبد الهادي الكحولي

تسجيل الخروج
بياناتي الشخصية
علبة الرسائل
تغيير كلمة المرور
العربية  الفرنسية
مرحبا عبد الهادي الكحولي,
تتبع النقط
السنة الدراسية

2021/2022
الدورة

الدورة الأولى

بيان النتائج الدراسية
المؤسسة
ثانوية القدس الإعدادية
المستوى
الثالثة إعدادي عام
Classe
3ASCG-5
عدد التلاميذ
42
نقط المراقبة المستمرة
بيان النتائج الدراسية
بيان النتائج الدراسية
المادة	الفرض الأول	الفرض الثاني	الفرض الثالث	الفرض الرابع	الأنشطة المندمجة
الاجتماعيات	10	11		16	
التربية الإسلامية	3,5	5		8	
التربية البدنية	16	16	16		
التربية التشكيلية	15	15			
الرياضيات	15	11,25	14		
الفيزياء والكيمياء	18,5	16,5	14,5	16	
اللغة الإنجليزية	17	11,5		13	
اللغة العربية	7	11,5		11	
اللغة الفرنسية	12,5	11	9	12	10
علوم الحياة والأرض	13	10,5		16	
إغلاق
فضائي التعاوني
